web:
  environment: 
    - DB_USER=$DB_USER
    - DB_PASSWORD=$DB_PASSWORD
    - DB_HOST=$DB_HOST
    - DB_PORT=$DB_PORT
    - DB_DATABASE=$DB_DATABASE
    - DB_URI:$DB_URI
  build: .
  ports:
   - "5000:5000"
  # volumes:
  #  - ./backend:/app/backend