POST http://localhost:5000/add-user
content-type: application/json

{
    "name": "Joseph Villegas 2",
    "email": "jovillegas@csumb.edu",
    "age": 21 
}
###
GET http://localhost:5000/api/test-sqlalchemy-get?name=Joseph%20Villegas&email=jovillegas@csumb.edu&age=21&test=hey
content-type: application/json
